apiVersion: batch/v1
kind: Job
metadata:
  namespace: web-app-production
  generateName: db-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: netkuy/web-app:ae97c1f-35
          command: [ "./migrate.sh" ]
