apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      run: app
  template:
    spec:
      containers:
        - name: app
          image: netkuy/web-app:8c39012-36
